import type { TranslationSentence } from './types';

// Production practice: the learner translates each Uzbek sentence into
// English themselves (in a plain textarea, never submitted anywhere), then
// taps to reveal `en` and self-checks — the app never grades these. Served a
// few at a time per unit via getNextSentenceBatch in lib/storage.ts.
//
// Authored fresh for this feature (not from either source PDF) — review for
// naturalness before relying on them, same as the other Uzbek content in
// lib/structures-data.ts.
export const TRANSLATION_SENTENCES: TranslationSentence[] = [
  // ─── Speaking Part 1 (8) ──────────────────────────────────────────────────
  { id: 'sent-sp1-01', unit: 'Speaking Part 1', structureId: 'struct-06',
    uz: "Agar tanlashim kerak bo'lsa, choyni kofedan ko'ra ko'proq yoqtiraman deb aytardim.",
    en: "If I had to choose, I'd say I prefer tea over coffee." },
  { id: 'sent-sp1-02', unit: 'Speaking Part 1', structureId: 'struct-06',
    uz: "Agar tanlashim kerak bo'lsa, dam olish kunlarini shaharda o'tkazishni afzal ko'raman deyman.",
    en: "If I had to choose, I'd say I prefer to spend weekends in the city." },
  { id: 'sent-sp1-03', unit: 'Speaking Part 1', structureId: 'struct-09',
    uz: "Ish juda charchatuvchi. Aytmoqchimanki, menga ko'proq dam kerak.",
    en: "The job is very tiring. What I mean is, I need more rest." },
  { id: 'sent-sp1-04', unit: 'Speaking Part 1', structureId: 'struct-09',
    uz: "U doim band. Aytmoqchimanki, u hech qachon bo'sh vaqtga ega emas.",
    en: "She's always busy. What I mean is, she never has free time." },
  { id: 'sent-sp1-05', unit: 'Speaking Part 1', structureId: 'struct-19',
    uz: "Odatda men ish kunining oxirida kitob o'qiyman.",
    en: "What I tend to do is read a book at the end of the workday." },
  { id: 'sent-sp1-06', unit: 'Speaking Part 1', structureId: 'struct-19',
    uz: "Odatda men dam olish kunlarida oilam bilan sayr qilaman.",
    en: "What I tend to do on weekends is go for a walk with my family." },
  { id: 'sent-sp1-07', unit: 'Speaking Part 1', structureId: 'struct-23',
    uz: "Do'stim bilan uchrashish uchun tashqarida edim.",
    en: "I was out meeting a friend." },
  { id: 'sent-sp1-08', unit: 'Speaking Part 1', structureId: 'struct-23',
    uz: "Kitob sotib olish uchun tashqarida ekanimda yomg'ir yog'a boshladi.",
    en: "I was out buying a book when it started to rain." },

  // ─── Speaking Part 2 (18) ─────────────────────────────────────────────────
  { id: 'sent-sp2-01', unit: 'Speaking Part 2', structureId: 'struct-01',
    uz: "Kontsert shunchalik ajoyib ediki, men uni hech qachon unutmayman.",
    en: "The concert was so amazing that I will never forget it." },
  { id: 'sent-sp2-02', unit: 'Speaking Part 2', structureId: 'struct-03',
    uz: "Faqat har kuni gapirish orqaligina ingliz tilimni yaxshiladim.",
    en: "Only by speaking every day did I improve my English." },
  { id: 'sent-sp2-03', unit: 'Speaking Part 2', structureId: 'struct-04',
    uz: "Muhimi — sayohat paytida yangi odamlar bilan tanishishdir.",
    en: "What's important is meeting new people while traveling." },
  { id: 'sent-sp2-04', unit: 'Speaking Part 2', structureId: 'struct-13',
    uz: "Faqat kollejga borgandagina mustaqillikning qadriga yetdim.",
    en: "It is not until I went to college that I appreciated independence." },
  { id: 'sent-sp2-05', unit: 'Speaking Part 2', structureId: 'struct-15',
    uz: "Uy egasi ketishi bilanoq yomg'ir boshlandi.",
    en: "No sooner had the host left than it began to rain." },
  { id: 'sent-sp2-06', unit: 'Speaking Part 2', structureId: 'struct-16',
    uz: "Faqat sinov topshirgandagina qanchalik tayyor emasligimni angladim.",
    en: "Only when I took the test did I realize how unprepared I was." },
  { id: 'sent-sp2-07', unit: 'Speaking Part 2', structureId: 'struct-20',
    uz: "Bu safar eng yaxshisi emas edi desam, yolg'on gapirgan bo'lardim.",
    en: "I'd be lying if I said this trip wasn't the best one." },
  { id: 'sent-sp2-08', unit: 'Speaking Part 2', structureId: 'struct-21',
    uz: "Chiroqni o'chirishim bilanoq telefonim jiringladi.",
    en: "Hardly had I turned off the light when my phone rang." },
  { id: 'sent-sp2-09', unit: 'Speaking Part 2', structureId: 'struct-26',
    uz: "Sovg'a yanada qimmatli tuyuldi, chunki uni o'zi qo'lda yasagan edi.",
    en: "The gift felt all the more special because she made it herself." },
  { id: 'sent-sp2-10', unit: 'Speaking Part 2', structureId: 'struct-30',
    uz: "Bilet allaqachon sotib olingan, va bo'lib o'tgan ish — o'tdi.",
    en: "The ticket is already bought, and what's done is done." },
  { id: 'sent-sp2-11', unit: 'Speaking Part 2', structureId: 'struct-31',
    uz: "O'yga cho'msam, o'sha sayohatni juda sog'inibman.",
    en: "Come to think of it, I really miss that trip." },
  { id: 'sent-sp2-12', unit: 'Speaking Part 2', structureId: 'struct-43',
    uz: "Kamida aytganda, mehmonxona xonasi kichkina edi.",
    en: "The hotel room was tiny, to say the least." },
  { id: 'sent-sp2-13', unit: 'Speaking Part 2', structureId: 'struct-59',
    uz: "U kechikishini oldindan aytdi va shu bilan bizga rejalashtirish imkonini berdi.",
    en: "She warned us about the delay, and in so doing, gave us time to plan." },
  { id: 'sent-sp2-14', unit: 'Speaking Part 2', structureId: 'struct-61',
    uz: "Uni boshqalardan ajratib turadigan jihat — uning sabr-toqatidir.",
    en: "What sets him apart is his patience." },
  { id: 'sent-sp2-15', unit: 'Speaking Part 2', structureId: 'struct-70',
    uz: "Ko'rganlarimga qaraganda, mehmondo'stlik bu yerda juda kuchli.",
    en: "From what I've seen, hospitality here is very strong." },
  { id: 'sent-sp2-16', unit: 'Speaking Part 2', structureId: 'struct-75',
    uz: "Omadimdan, chiptalar hali ham mavjud edi.",
    en: "As luck would have it, the tickets were still available." },
  { id: 'sent-sp2-17', unit: 'Speaking Part 2', structureId: 'struct-76',
    uz: "Orqaga qarab aytganda, o'sha imkoniyatni qo'ldan boy bermasligim kerak edi.",
    en: "In hindsight, I shouldn't have missed that opportunity." },
  { id: 'sent-sp2-18', unit: 'Speaking Part 2', structureId: 'struct-79',
    uz: "Xavfsizlik uchun barcha hujjatlarimni oldindan tayyorlab qo'ydim.",
    en: "To be on the safe side, I prepared all my documents in advance." },

  // ─── Speaking Part 3 (18) ─────────────────────────────────────────────────
  { id: 'sent-sp3-01', unit: 'Speaking Part 3', structureId: 'struct-02',
    uz: "Agar oilamning yordami bo'lmaganida, bu qadar uzoqqa yeta olmasdim.",
    en: "Were it not for my family's support, I wouldn't have come this far." },
  { id: 'sent-sp3-02', unit: 'Speaking Part 3', structureId: 'struct-08',
    uz: "Menimcha, maktablar amaliy ko'nikmalarga ko'proq e'tibor berishi kerak.",
    en: "The way I see it, schools should focus more on practical skills." },
  { id: 'sent-sp3-03', unit: 'Speaking Part 3', structureId: 'struct-11',
    uz: "Odamlarning ijtimoiy tarmoqlardan foydalanishining asosiy sabablaridan biri — bog'lanib turishdir.",
    en: "One of the main reasons people use social media is to stay connected." },
  { id: 'sent-sp3-04', unit: 'Speaking Part 3', structureId: 'struct-14',
    uz: "Ko'plab yoshlarning shaharlarga ko'chib o'tishining sababi shundaki, u yerda ko'proq ish imkoniyati bor.",
    en: "The reason why many young people move to cities is that there are more job opportunities." },
  { id: 'sent-sp3-05', unit: 'Speaking Part 3', structureId: 'struct-18',
    uz: "Menimcha, davlat ta'limga ko'proq mablag' ajratishi kerak.",
    en: "As far as I'm concerned, the government should invest more in education." },
  { id: 'sent-sp3-06', unit: 'Speaking Part 3', structureId: 'struct-25',
    uz: "Aksincha, bu qiyinchilik meni yanada kuchliroq qildi.",
    en: "If anything, this hardship made me stronger." },
  { id: 'sent-sp3-07', unit: 'Speaking Part 3', structureId: 'struct-29',
    uz: "Shunday bo'lsa-da, hukumat harakat qilishi kerak.",
    en: "Be that as it may, the government must take action." },
  { id: 'sent-sp3-08', unit: 'Speaking Part 3', structureId: 'struct-33',
    uz: "Ko'pincha bo'lgani kabi, yosh avlod texnologiyaga tezroq moslashadi.",
    en: "As is often the case, the younger generation adapts to technology faster." },
  { id: 'sent-sp3-09', unit: 'Speaking Part 3', structureId: 'struct-37',
    uz: "Mantiqan, ko'proq mashq qilgan odam yaxshiroq natijaga erishadi.",
    en: "It stands to reason that someone who practices more achieves better results." },
  { id: 'sent-sp3-10', unit: 'Speaking Part 3', structureId: 'struct-40',
    uz: "Tanqidlarga qaramasdan, loyiha davom ettirildi.",
    en: "Notwithstanding the criticism, the project was continued." },
  { id: 'sent-sp3-11', unit: 'Speaking Part 3', structureId: 'struct-47',
    uz: "Ta'limning hayotni o'zgartirishini inkor etib bo'lmaydi.",
    en: "There's no denying that education changes lives." },
  { id: 'sent-sp3-12', unit: 'Speaking Part 3', structureId: 'struct-49',
    uz: "So'nggi statistika asosida siyosat qayta ko'rib chiqildi.",
    en: "In light of the latest statistics, the policy was reviewed." },
  { id: 'sent-sp3-13', unit: 'Speaking Part 3', structureId: 'struct-56',
    uz: "Bu pul muammosi emas, aslida vaqt yetishmasligidir.",
    en: "It's not so much a money problem as a lack of time." },
  { id: 'sent-sp3-14', unit: 'Speaking Part 3', structureId: 'struct-65',
    uz: "Uning muvaffaqiyatga erishishi tasodif emas — u har kuni mashq qilgan.",
    en: "It's no coincidence that she succeeded — she practiced every day." },
  { id: 'sent-sp3-15', unit: 'Speaking Part 3', structureId: 'phrase-11',
    uz: "Global sayohat ikki tomonlama pichoq kabi — u madaniyatlarni bog'laydi, lekin ekologiyaga zarar yetkazadi.",
    en: "Global travel is a double-edged sword — it connects cultures but harms the environment." },
  { id: 'sent-sp3-16', unit: 'Speaking Part 3', structureId: 'phrase-25',
    uz: "Trafik tirbandligini kamaytirish uchun barchaga mos yagona yechim yo'q.",
    en: "There's no one-size-fits-all solution to reducing traffic congestion." },
  { id: 'sent-sp3-17', unit: 'Speaking Part 3', structureId: 'phrase-38',
    uz: "Ushbu bahsning har ikki tomonida ham asosli argumentlar bor.",
    en: "There are valid arguments on both sides of this debate." },
  { id: 'sent-sp3-18', unit: 'Speaking Part 3', structureId: 'phrase-63',
    uz: "Erkin ishlash mustaqillikni oshiradi, deb da'vo qilish mumkin.",
    en: "There's an argument to be made that freelancing increases independence." },

  // ─── Writing Task 2 (18) ──────────────────────────────────────────────────
  { id: 'sent-wt2-01', unit: 'Writing Task 2', structureId: 'struct-74',
    uz: "Shunga qaramay, ko'p oilalar hali ham qashshoqlikda yashaydi, bu haqiqat o'zgarmaydi.",
    en: "The fact remains that many families still live in poverty." },
  { id: 'sent-wt2-02', unit: 'Writing Task 2', structureId: 'phrase-03',
    uz: "Bu asosan qishloq joylardagi ish imkoniyatlarining yetishmasligi sababli.",
    en: "This is largely due to the lack of job opportunities in rural areas." },
  { id: 'sent-wt2-03', unit: 'Writing Task 2', structureId: 'phrase-07',
    uz: "Buni ta'lim tizimidagi islohotlar bilan izohlash mumkin.",
    en: "This can be attributed to reforms in the education system." },
  { id: 'sent-wt2-04', unit: 'Writing Task 2', structureId: 'phrase-12',
    uz: "Muammoning ildizi zaif infratuzilmada yotibdi.",
    en: "The root of the problem lies in weak infrastructure." },
  { id: 'sent-wt2-05', unit: 'Writing Task 2', structureId: 'phrase-16',
    uz: "Asosiy tashvish shundaki, yosh avlod amaliy ko'nikmalarga ega emas.",
    en: "The main concern is that the younger generation lacks practical skills." },
  { id: 'sent-wt2-06', unit: 'Writing Task 2', structureId: 'phrase-21',
    uz: "Onlayn ta'limning foydalari kamchiliklaridan ustun.",
    en: "The benefits of online education outweigh the drawbacks." },
  { id: 'sent-wt2-07', unit: 'Writing Task 2', structureId: 'phrase-32',
    uz: "Bu ota-onalarning yetarli nazorat qilmasligi natijasi bo'lishi mumkin.",
    en: "This might be the result of insufficient parental supervision." },
  { id: 'sent-wt2-08', unit: 'Writing Task 2', structureId: 'phrase-34',
    uz: "Agar e'tiborsiz qoldirilsa, iqlim o'zgarishining oqibatlari jiddiy bo'lishi mumkin.",
    en: "If ignored, the consequences of climate change could be serious." },
  { id: 'sent-wt2-09', unit: 'Writing Task 2', structureId: 'phrase-39',
    uz: "Ishsizlikning ortishi iqtisodiyotdagi chuqurroq muammoni aks ettiradi.",
    en: "The rise in unemployment reflects a deeper issue in the economy." },
  { id: 'sent-wt2-10', unit: 'Writing Task 2', structureId: 'phrase-42',
    uz: "Agar hozirgi tendensiya davom etsa, katta shaharlar yanada gavjum bo'ladi.",
    en: "If current trends continue, major cities will become even more crowded." },
  { id: 'sent-wt2-11', unit: 'Writing Task 2', structureId: 'phrase-44',
    uz: "Sun'iy intellektning rivojlanishi axloqiy savollarni keltirib chiqaradi.",
    en: "The development of artificial intelligence raises ethical questions." },
  { id: 'sent-wt2-12', unit: 'Writing Task 2', structureId: 'phrase-45',
    uz: "Dalillar ta'lim va daromad o'rtasidagi bog'liqlikka ishora qilmoqda.",
    en: "The evidence points to a link between education and income." },
  { id: 'sent-wt2-13', unit: 'Writing Task 2', structureId: 'phrase-48',
    uz: "Plastik ifloslanishining ta'sirini e'tiborsiz qoldirish tobora qiyinlashmoqda.",
    en: "It's becoming harder to ignore the effects of plastic pollution." },
  { id: 'sent-wt2-14', unit: 'Writing Task 2', structureId: 'phrase-53',
    uz: "Boy va kambag'al mamlakatlar o'rtasidagi tafovut kengaymoqda.",
    en: "The gap is widening between rich and poor countries." },
  { id: 'sent-wt2-15', unit: 'Writing Task 2', structureId: 'phrase-59',
    uz: "Ekologik mahsulotlarga bo'lgan talab qadriyatlardagi o'zgarishni aks ettiradi.",
    en: "The demand for eco-friendly products reflects a change in values." },
  { id: 'sent-wt2-16', unit: 'Writing Task 2', structureId: 'phrase-65',
    uz: "Global isishning voqeligi ko'rinishidan ko'ra murakkabroq.",
    en: "The reality of global warming is more complex than it seems." },
  { id: 'sent-wt2-17', unit: 'Writing Task 2', structureId: 'phrase-72',
    uz: "Yangi soliqni joriy qilish kichik bizneslar uchun kutilmagan oqibatlarga olib kelishi mumkin.",
    en: "Introducing the new tax may have unintended consequences for small businesses." },
  { id: 'sent-wt2-18', unit: 'Writing Task 2', structureId: 'phrase-76',
    uz: "Masofaviy ish an'anaviy karyera tushunchasiga qarshi chiqadi.",
    en: "Remote work challenges the traditional idea of a career." },
];
